# Generated by Django 6.0.6 on 2026-06-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='gender',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='personnel',
            name='nationality',
            field=models.CharField(default='TR', max_length=3),
        ),
        migrations.AddField(
            model_name='personnel',
            name='src_codes',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='personnel',
            name='uetds_role_code',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
