# Generated by Django 6.0.6 on 2026-06-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_personnel_address_personnel_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='uetds_role_code',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
