# Generated by Django 6.0.6 on 2026-06-12 22:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plate', models.CharField(max_length=16)),
                ('brand', models.CharField(blank=True, max_length=80)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('seat_capacity', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('passive', 'Passive')], default='active', max_length=16)),
                ('uetds_status', models.CharField(choices=[('unknown', 'Unknown'), ('valid', 'Valid'), ('invalid', 'Invalid')], default='unknown', max_length=16)),
                ('uetds_last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
            ],
            options={
                'ordering': ['plate'],
                'unique_together': {('company', 'plate')},
            },
        ),
    ]
