# Generated by Django 6.0.6 on 2026-06-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
