# Generated by Django 6.0.6 on 2026-07-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_vehicle_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='uetds_authorization_document_no',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='uetds_authorization_document_type',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='uetds_company_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='uetds_unet_no',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
