# Generated by Django 6.0.6 on 2026-06-12 22:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('identity_type', models.CharField(choices=[('tc', 'TC'), ('passport', 'Passport'), ('foreign_id', 'Foreign ID'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('identity_no', models.CharField(blank=True, max_length=64, null=True)),
                ('nationality', models.CharField(default='TR', max_length=3)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
                'indexes': [models.Index(fields=['company', 'first_name', 'last_name'], name='passengers__company_a15b9f_idx'), models.Index(fields=['company', 'identity_no'], name='passengers__company_5d1d45_idx')],
            },
        ),
    ]
