# Generated by Django 6.0.6 on 2026-06-12 22:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('fleet', '0001_initial'),
        ('passengers', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('city', models.CharField(max_length=120)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('address', models.TextField(blank=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
            ],
            options={
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip_type', models.CharField(choices=[('transfer', 'Transfer'), ('tour', 'Tour'), ('shuttle', 'Shuttle'), ('vip', 'VIP'), ('other', 'Other')], default='transfer', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('submitting', 'Submitting'), ('submitted', 'Submitted'), ('partial_failed', 'Partial Failed'), ('failed', 'Failed'), ('cancel_requested', 'Cancel Requested'), ('cancelled', 'Cancelled')], default='draft', max_length=24)),
                ('departure_at', models.DateTimeField()),
                ('arrival_estimated_at', models.DateTimeField(blank=True, null=True)),
                ('departure_city', models.CharField(max_length=120)),
                ('departure_district', models.CharField(blank=True, max_length=120)),
                ('departure_address', models.TextField()),
                ('arrival_city', models.CharField(max_length=120)),
                ('arrival_district', models.CharField(blank=True, max_length=120)),
                ('arrival_address', models.TextField()),
                ('route_note', models.TextField(blank=True)),
                ('passenger_count', models.PositiveIntegerField(default=0)),
                ('uetds_reference_no', models.CharField(blank=True, max_length=64, null=True)),
                ('uetds_environment', models.CharField(default='test', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_trips', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driver_trips', to='people.personnel')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-departure_at'],
            },
        ),
        migrations.CreateModel(
            name='TripPassenger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seat_no', models.CharField(blank=True, max_length=16)),
                ('uetds_passenger_reference_no', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('not_arrived', 'Not Arrived')], default='active', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_links', to='passengers.passenger')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_passengers', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripPersonnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(default='driver', max_length=32)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_links', to='people.personnel')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_personnel', to='trips.trip')),
            ],
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['company', 'status', 'departure_at'], name='trips_trip_company_b51df5_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['company', 'uetds_reference_no'], name='trips_trip_company_66528c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trippassenger',
            unique_together={('trip', 'passenger')},
        ),
        migrations.AlterUniqueTogether(
            name='trippersonnel',
            unique_together={('trip', 'personnel', 'role')},
        ),
    ]
