# Generated by Django 6.0.6 on 2026-06-16 21:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='firm_trip_no',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='TripGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='TRANSFER', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='TRY', max_length=3)),
                ('departure_country', models.CharField(default='TR', max_length=3)),
                ('departure_city', models.CharField(blank=True, max_length=120)),
                ('departure_district', models.CharField(blank=True, max_length=120)),
                ('departure_city_code', models.CharField(blank=True, max_length=16)),
                ('departure_district_code', models.CharField(blank=True, max_length=16)),
                ('departure_place', models.CharField(blank=True, max_length=255)),
                ('arrival_country', models.CharField(default='TR', max_length=3)),
                ('arrival_city', models.CharField(blank=True, max_length=120)),
                ('arrival_district', models.CharField(blank=True, max_length=120)),
                ('arrival_city_code', models.CharField(blank=True, max_length=16)),
                ('arrival_district_code', models.CharField(blank=True, max_length=16)),
                ('arrival_place', models.CharField(blank=True, max_length=255)),
                ('uetds_group_ref_no', models.CharField(blank=True, max_length=64, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='trips.trip')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='trippassenger',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passenger_links', to='trips.tripgroup'),
        ),
    ]
