# Generated by Django 6.0.6 on 2026-06-21 21:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('trips', '0002_trip_description_trip_firm_trip_no_tripgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('departure_country', models.CharField(default='TR', max_length=3)),
                ('departure_city', models.CharField(max_length=120)),
                ('departure_district', models.CharField(blank=True, max_length=120)),
                ('departure_city_code', models.CharField(blank=True, max_length=16)),
                ('departure_district_code', models.CharField(blank=True, max_length=16)),
                ('departure_place', models.CharField(max_length=255)),
                ('departure_address', models.TextField(blank=True)),
                ('arrival_country', models.CharField(default='TR', max_length=3)),
                ('arrival_city', models.CharField(max_length=120)),
                ('arrival_district', models.CharField(blank=True, max_length=120)),
                ('arrival_city_code', models.CharField(blank=True, max_length=16)),
                ('arrival_district_code', models.CharField(blank=True, max_length=16)),
                ('arrival_place', models.CharField(max_length=255)),
                ('arrival_address', models.TextField(blank=True)),
                ('default_group_name', models.CharField(default='TRANSFER', max_length=120)),
                ('default_group_description', models.TextField(blank=True)),
                ('default_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='TRY', max_length=3)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
            ],
            options={
                'ordering': ['-usage_count', 'name'],
            },
        ),
    ]
