# Generated by Codex on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0003_savedroute"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedlocation",
            name="country",
            field=models.CharField(default="TR", max_length=3),
        ),
        migrations.AddField(
            model_name="savedlocation",
            name="city_code",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="savedlocation",
            name="district_code",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="savedlocation",
            name="place",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
