# Generated by Codex on 2026-07-18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0004_savedlocation_uetds_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="trip_type",
        ),
    ]
