# Generated by Django 6.0.6 on 2026-07-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_remove_trip_trip_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='uetds_last_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='uetds_last_submitted_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='trip',
            name='uetds_last_submitted_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
