# Generated by Django 6.0.6 on 2026-06-12 22:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UETDSOperationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.CharField(choices=[('kullaniciKontrol', 'Kullanici Kontrol'), ('ipListele', 'IP Listele'), ('yetkiBelgesiKontrol', 'Yetki Belgesi Kontrol'), ('aracMuayeneSorgula', 'Arac Muayene Sorgula'), ('seferEkle', 'Sefer Ekle'), ('personelEkle', 'Personel Ekle'), ('yolcuEkleCoklu', 'Yolcu Ekle Coklu'), ('bildirimOzeti', 'Bildirim Ozeti'), ('seferIptal', 'Sefer Iptal')], max_length=64)),
                ('environment', models.CharField(default='test', max_length=16)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('uetds_sonuc_kodu', models.CharField(blank=True, max_length=32)),
                ('uetds_sonuc_mesaji', models.TextField(blank=True)),
                ('request_xml', models.TextField(blank=True)),
                ('response_xml', models.TextField(blank=True)),
                ('correlation_id', models.CharField(blank=True, max_length=128)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uetds_logs', to='trips.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UETDSOperationStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
                ('last_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uetds.uetdsoperationlog')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uetds_steps', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=128)),
                ('endpoint', models.CharField(max_length=128)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('status_code', models.PositiveSmallIntegerField(default=200)),
                ('completed', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to='trips.trip')),
            ],
            options={
                'unique_together': {('company', 'key', 'endpoint')},
            },
        ),
        migrations.CreateModel(
            name='UETDSCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.CharField(choices=[('test', 'Test'), ('live', 'Live')], max_length=16)),
                ('username_encrypted', models.TextField()),
                ('password_encrypted', models.TextField()),
                ('endpoint_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_result', models.CharField(blank=True, max_length=32)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
            ],
            options={
                'unique_together': {('company', 'environment')},
            },
        ),
        migrations.AddIndex(
            model_name='uetdsoperationlog',
            index=models.Index(fields=['company', 'operation', 'success'], name='uetds_uetds_company_568225_idx'),
        ),
        migrations.AddIndex(
            model_name='uetdsoperationlog',
            index=models.Index(fields=['company', 'trip'], name='uetds_uetds_company_ccedcf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='uetdsoperationstep',
            unique_together={('trip', 'operation')},
        ),
    ]
