# Generated by Django 6.0.6 on 2026-06-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uetds', '0002_alter_uetdsoperationlog_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uetdsoperationlog',
            name='operation',
            field=models.CharField(choices=[('kullaniciKontrol', 'Kullanici Kontrol'), ('ipListele', 'IP Listele'), ('yetkiBelgesiKontrol', 'Yetki Belgesi Kontrol'), ('aracMuayeneSorgula', 'Arac Muayene Sorgula'), ('credentialCheck', 'Credential Check'), ('seferEkle', 'Sefer Ekle'), ('seferGrupEkle', 'Sefer Grup Ekle'), ('personelEkle', 'Personel Ekle'), ('yolcuEkleCoklu', 'Yolcu Ekle Coklu'), ('bildirimOzeti', 'Bildirim Ozeti'), ('seferIptal', 'Sefer Iptal')], max_length=64),
        ),
    ]
