# Generated by Django 6.0.6 on 2026-07-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uetds', '0004_alter_uetdsoperationlog_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uetdsoperationlog',
            name='operation',
            field=models.CharField(choices=[('kullaniciKontrol', 'Kullanici Kontrol'), ('ipListele', 'IP Listele'), ('yetkiBelgesiKontrol', 'Yetki Belgesi Kontrol'), ('aracMuayeneSorgula', 'Arac Muayene Sorgula'), ('credentialCheck', 'Credential Check'), ('seferEkle', 'Sefer Ekle'), ('seferGuncelle', 'Sefer Guncelle'), ('seferPlakaDegistir', 'Sefer Plaka Degistir'), ('seferGrupEkle', 'Sefer Grup Ekle'), ('seferGrupGuncelle', 'Sefer Grup Guncelle'), ('personelEkle', 'Personel Ekle'), ('personelIptal', 'Personel Iptal'), ('yolcuEkleCoklu', 'Yolcu Ekle Coklu'), ('yolcuIptal', 'Yolcu Iptal'), ('bildirimOzeti', 'Bildirim Ozeti'), ('seferIptal', 'Sefer Iptal')], max_length=64),
        ),
    ]
