# Generated by Codex on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysettings",
            name="ai_passenger_parse_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="companysettings",
            name="ai_passenger_parse_monthly_token_limit",
            field=models.PositiveIntegerField(default=50000),
        ),
        migrations.AddField(
            model_name="companysettings",
            name="ai_passenger_parse_monthly_tokens_used",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="companysettings",
            name="ai_passenger_parse_usage_month",
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
